import { StyleSheet } from "react-native";
export const login = StyleSheet.create({
    boxLogin: {
        flex: 1,
        justifyContent: "center",
        position: "relative",
        backgroundColor: "#22577A",
        alignItems: "center",
    },
    imgEl:{
        width: 170,
        height: 100,
        top: 100,
        left: 30,
        position:"absolute",
        resizeMode: "contain",
        zIndex: 3
    },
    overlay: {
        backgroundColor: "rgba(22, 22, 22, 0.56)", // Um leve escurecimento por cima da imagem
        padding: 20,
        borderRadius: 10,
    },

    textLogin: {
        position: "absolute",
        zIndex: 3,
        top: 235,
        left:120,
        color: "#fff",
        fontSize: 34,  
        fontWeight: "bold",
        marginTop: 50,
    },

    EfeitoOne: {
        width: 300,
        height: 300,
        backgroundColor: '#C7F9CC',
        borderRadius: 200,
        position: 'absolute',
        top: "-9%",
        right: "-20%",
        zIndex: 2,
    },
    EfeitoTwo: {
        width: 100,
        height: 100,
        backgroundColor: '#a7d2abff',
        borderRadius: 200,
        position: 'absolute',
        top: "14%",
        right: "-10%",
        zIndex: 2,
    },
    EfeitoThree: {
        width: 850,
        height: 850,
        backgroundColor: '#a7d2abff',
        borderRadius: "50%",
        position: 'absolute',
        bottom: "-50%",
        zIndex: 2,
    },
    EfeitoFor: {
        width: 250,
        height: 250,
        backgroundColor: '#C7F9CC',
        borderRadius: "50%",
        position: 'absolute',
        bottom: -60,
        right: "-10%",
        zIndex: 2,
    },
    EfeitoFive: {
    position: "absolute",
    top: "-9%",
    left: "-30%",
    borderRadius: "50%",
    backgroundColor: "#1e4f6fd4",
    width: 600, 
    height: 600,
    zIndex: 1,
    },

    form:{
        width: "100%",
        height: "50%",
        // backgroundColor: "#fff",
        // position: "absolute",
        zIndex: 3,
        display:"flex",
        justifyContent: "center",
        alignItems:  "center",
    },

    buttonLogin: {
        position: "absolute",
        bottom: 80,
        width: "80%",
        marginTop: 20,
        backgroundColor: "#38A3A5",
        paddingVertical: 15,
        borderRadius: 5,
        zIndex: 3,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    textButtonLogin: {
        color: "#fff",
        fontSize: 19,  
        fontWeight: "bold",
        textAlign: "center",
    },

});